# Generated by Django 5.0.8 on 2025-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Certi_Title", models.CharField(max_length=150)),
                ("Certi_Duration", models.CharField(max_length=150)),
                ("Certi_Institution", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Education_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150)),
                ("Duration", models.CharField(max_length=150)),
                ("Institution", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Experience_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150)),
                ("Duration", models.CharField(max_length=150)),
                ("Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="general_info_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField(max_length=10)),
                ("website_title", models.CharField(max_length=100)),
                ("site_title", models.CharField(max_length=100)),
                ("facebook_url", models.CharField(max_length=500, null=True)),
                ("instagram_url", models.CharField(max_length=500, null=True)),
                ("twitter_url", models.CharField(max_length=500, null=True)),
                ("github_url", models.CharField(max_length=500, null=True)),
                ("linkedin_url", models.CharField(max_length=500, null=True)),
                ("resume_url", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Project_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150)),
                ("Description", models.TextField()),
                ("Video_link", models.FileField(upload_to="Skill/")),
                ("Skills_learned", models.JSONField()),
                ("GitHub_link", models.CharField(max_length=150, null=True)),
                ("Visit_link", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150)),
                ("Icon", models.FileField(upload_to="Skill/")),
                ("ToShow", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="homepage_model",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="homepage_model",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="homepage_model",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="homepage_model",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="homepage_model",
            name="resume_url",
        ),
        migrations.RemoveField(
            model_name="homepage_model",
            name="twitter_url",
        ),
    ]
